version: '3'

services:
  server:
    image: server
    ports:
      - "3000:3000"
  client:
    image: client
    stdin_open: true
    tty: true
    user: $UID:$GID
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
      - "3001:3001"
    depends_on:
      - server
    
        
